using System.Text;
using xpTURN.Klotho.Generator.Model;

namespace xpTURN.Klotho.Generator.Emitters
{
    internal static class CommandEmitter
    {
        public static string Emit(SerializableTypeInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using xpTURN.Klotho.Deterministic.Math;");
            sb.AppendLine("using xpTURN.Klotho.Serialization;");
            sb.AppendLine();

            if (info.Namespace != null)
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            var indent = info.Namespace != null ? "    " : "";
            sb.AppendLine($"{indent}partial class {info.TypeName}");
            sb.AppendLine($"{indent}{{");

            if (info.TypeId.HasValue)
            {
                sb.AppendLine($"{indent}    public const int TYPE_ID = {info.TypeId.Value};");
                sb.AppendLine($"{indent}    public override int CommandTypeId => TYPE_ID;");
                sb.AppendLine();
            }

            if (!info.HasManualSerialization)
            {
                EmitHelper.EmitGetSerializedSize(sb, info, indent);
                sb.AppendLine();
                EmitSerializeData(sb, info, indent);
                sb.AppendLine();
                EmitDeserializeData(sb, info, indent);
            }

            sb.AppendLine($"{indent}}}");

            if (info.Namespace != null)
                sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitSerializeData(StringBuilder sb, SerializableTypeInfo info, string indent)
        {
            sb.AppendLine($"{indent}    protected override void SerializeData(ref SpanWriter writer)");
            sb.AppendLine($"{indent}    {{");

            if (info.Fields.Count == 0)
            {
                // Empty body for EmptyCommand-like types
            }
            else
            {
                foreach (var field in info.Fields)
                {
                    EmitHelper.EmitSerializeField(sb, field, $"{indent}        ");
                }
            }

            sb.AppendLine($"{indent}    }}");
        }

        private static void EmitDeserializeData(StringBuilder sb, SerializableTypeInfo info, string indent)
        {
            sb.AppendLine($"{indent}    protected override void DeserializeData(ref SpanReader reader)");
            sb.AppendLine($"{indent}    {{");

            if (info.Fields.Count == 0)
            {
                // Empty body
            }
            else
            {
                foreach (var field in info.Fields)
                {
                    EmitHelper.EmitDeserializeField(sb, field, $"{indent}        ");
                }
            }

            sb.AppendLine($"{indent}    }}");
        }
    }
}
