using System.Text;
using xpTURN.Klotho.Generator.Model;
using xpTURN.Klotho.Generator.Utils;

namespace xpTURN.Klotho.Generator.Emitters
{
    internal static class ComponentEmitter
    {
        private static bool HasFixedFields(ComponentTypeInfo info)
        {
            foreach (var f in info.Fields)
                if (f.IsFixed) return true;
            return false;
        }

        public static string Emit(ComponentTypeInfo info)
        {
            bool hasFixed = HasFixedFields(info);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using xpTURN.Klotho.Deterministic.Math;");
            sb.AppendLine("using xpTURN.Klotho.Deterministic;");
            sb.AppendLine("using xpTURN.Klotho.ECS;");
            sb.AppendLine("using xpTURN.Klotho.Serialization;");
            sb.AppendLine();

            if (info.Namespace != null)
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            var indent = info.Namespace != null ? "    " : "";
            var unsafeModifier = hasFixed ? "unsafe " : "";
            sb.AppendLine($"{indent}{unsafeModifier}partial struct {info.TypeName}");
            sb.AppendLine($"{indent}{{");

            sb.AppendLine($"{indent}    public const int TYPE_ID = {info.ComponentTypeId};");
            sb.AppendLine();

            EmitSerialize(sb, info, indent);
            sb.AppendLine();
            EmitDeserialize(sb, info, indent);
            sb.AppendLine();
            EmitGetSerializedSize(sb, info, indent);
            sb.AppendLine();
            EmitGetHash(sb, info, indent);

            sb.AppendLine($"{indent}}}");

            if (info.Namespace != null)
                sb.AppendLine("}");

            sb.AppendLine();
            EmitStorageRegistrar(sb, info);

            return sb.ToString();
        }

        private static void EmitSerialize(StringBuilder sb, ComponentTypeInfo info, string indent)
        {
            bool hasFixed = HasFixedFields(info);
            var unsafeModifier = hasFixed ? "unsafe " : "";
            sb.AppendLine($"{indent}    public {unsafeModifier}void Serialize(ref SpanWriter writer)");
            sb.AppendLine($"{indent}    {{");

            foreach (var field in info.Fields)
            {
                if (field.IsFixed)
                {
                    if (TypeMappings.TryGetMapping(field.ElementType, out var elemMapping))
                    {
                        sb.AppendLine($"{indent}        fixed ({field.ElementType}* __p_{field.Name} = this.{field.Name})");
                        sb.AppendLine($"{indent}        {{");
                        sb.AppendLine($"{indent}            for (int __i = 0; __i < {field.FixedSize}; __i++) writer.{elemMapping.WriteMethod}(__p_{field.Name}[__i]);");
                        sb.AppendLine($"{indent}        }}");
                    }
                }
                else if (TypeMappings.TryGetMapping(field.TypeFullName, out var mapping))
                {
                    sb.AppendLine($"{indent}        writer.{mapping.WriteMethod}(this.{field.Name});");
                }
            }

            sb.AppendLine($"{indent}    }}");
        }

        private static void EmitDeserialize(StringBuilder sb, ComponentTypeInfo info, string indent)
        {
            bool hasFixed = HasFixedFields(info);
            var unsafeModifier = hasFixed ? "unsafe " : "";
            sb.AppendLine($"{indent}    public {unsafeModifier}void Deserialize(ref SpanReader reader)");
            sb.AppendLine($"{indent}    {{");

            foreach (var field in info.Fields)
            {
                if (field.IsFixed)
                {
                    if (TypeMappings.TryGetMapping(field.ElementType, out var elemMapping))
                    {
                        sb.AppendLine($"{indent}        fixed ({field.ElementType}* __p_{field.Name} = this.{field.Name})");
                        sb.AppendLine($"{indent}        {{");
                        sb.AppendLine($"{indent}            for (int __i = 0; __i < {field.FixedSize}; __i++) __p_{field.Name}[__i] = reader.{elemMapping.ReadMethod}();");
                        sb.AppendLine($"{indent}        }}");
                    }
                }
                else if (TypeMappings.TryGetMapping(field.TypeFullName, out var mapping))
                {
                    sb.AppendLine($"{indent}        this.{field.Name} = reader.{mapping.ReadMethod}();");
                }
            }

            sb.AppendLine($"{indent}    }}");
        }

        private static void EmitGetSerializedSize(StringBuilder sb, ComponentTypeInfo info, string indent)
        {
            int totalSize = 0;
            foreach (var field in info.Fields)
            {
                if (field.IsFixed)
                {
                    if (TypeMappings.TryGetMapping(field.ElementType, out var elemMapping) && elemMapping.Size > 0)
                        totalSize += elemMapping.Size * field.FixedSize;
                }
                else if (TypeMappings.TryGetMapping(field.TypeFullName, out var mapping) && mapping.Size > 0)
                {
                    totalSize += mapping.Size;
                }
            }

            sb.AppendLine($"{indent}    public int GetSerializedSize() => {totalSize};");
        }

        private static void EmitGetHash(StringBuilder sb, ComponentTypeInfo info, string indent)
        {
            bool hasFixed = HasFixedFields(info);
            var unsafeModifier = hasFixed ? "unsafe " : "";
            sb.AppendLine($"{indent}    public {unsafeModifier}ulong GetHash(ulong hash)");
            sb.AppendLine($"{indent}    {{");

            foreach (var field in info.Fields)
            {
                if (field.IsFixed)
                {
                    if (TypeMappings.TryGetMapping(field.ElementType, out var elemMapping) && elemMapping.HashExpression != null)
                    {
                        sb.AppendLine($"{indent}        fixed ({field.ElementType}* __p_{field.Name} = this.{field.Name})");
                        sb.AppendLine($"{indent}        {{");
                        sb.AppendLine($"{indent}            for (int __i = 0; __i < {field.FixedSize}; __i++) hash = {string.Format(elemMapping.HashExpression, "hash", $"__p_{field.Name}[__i]")};");
                        sb.AppendLine($"{indent}        }}");
                    }
                }
                else if (TypeMappings.TryGetMapping(field.TypeFullName, out var mapping) && mapping.HashExpression != null)
                {
                    var expr = string.Format(mapping.HashExpression, "hash", $"this.{field.Name}");
                    sb.AppendLine($"{indent}        hash = {expr};");
                }
            }

            sb.AppendLine($"{indent}        return hash;");
            sb.AppendLine($"{indent}    }}");
        }

        private static void EmitStorageRegistrar(StringBuilder sb, ComponentTypeInfo info)
        {
            var fullTypeName = info.Namespace != null
                ? $"{info.Namespace}.{info.TypeName}"
                : info.TypeName;

            // attach [xpTURN.Klotho.ECS.Preserve].
            // Unity IL2CPP skips stripping by attribute simple name "Preserve" — use a local definition.
            // (Runtime asmdef has noEngineReferences=true, so UnityEngine.Scripting.Preserve is unavailable.)
            // Effect: prevents removal of the [ModuleInitializer] entry point + generic
            //        ComponentReflector<T> chain even at Managed Stripping Level = Medium/High.
            sb.AppendLine("[xpTURN.Klotho.ECS.Preserve]");
            sb.AppendLine($"internal static class {info.TypeName}StorageRegistrar");
            sb.AppendLine("{");
            sb.AppendLine("    [ModuleInitializer]");
            sb.AppendLine("    [xpTURN.Klotho.ECS.Preserve]");
            sb.AppendLine("    internal static void Register()");
            sb.AppendLine("    {");
            sb.AppendLine($"        ComponentStorageRegistry.Register<{fullTypeName}>({fullTypeName}.TYPE_ID);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }
    }
}
