using System.Text;
using xpTURN.Klotho.Generator.Model;
using xpTURN.Klotho.Generator.Utils;

namespace xpTURN.Klotho.Generator.Emitters
{
    internal static class DataAssetEmitter
    {
        public static string Emit(DataAssetTypeInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using xpTURN.Klotho.Deterministic.Math;");
            sb.AppendLine("using xpTURN.Klotho.ECS;");
            sb.AppendLine("using xpTURN.Klotho.Serialization;");
            sb.AppendLine();

            if (info.Namespace != null)
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            var indent = info.Namespace != null ? "    " : "";
            sb.AppendLine($"{indent}partial class {info.TypeName} : IDataAssetSerializable");
            sb.AppendLine($"{indent}{{");

            sb.AppendLine($"{indent}    public const int TYPE_ID = {info.TypeId};");
            sb.AppendLine();

            EmitGetSerializedSize(sb, info, indent);
            sb.AppendLine();
            EmitSerialize(sb, info, indent);
            sb.AppendLine();
            EmitDeserialize(sb, info, indent);

            sb.AppendLine($"{indent}}}");

            if (info.Namespace != null)
                sb.AppendLine("}");

            sb.AppendLine();
            EmitRegistrar(sb, info);

            return sb.ToString();
        }

        private static void EmitGetSerializedSize(StringBuilder sb, DataAssetTypeInfo info, string indent)
        {
            int fixedSize = 4; // AssetId
            var variableParts = new StringBuilder();

            foreach (var field in info.Fields)
            {
                var (isFixed, size, variableExpr) = EmitHelper.GetSizeExpression(field);
                if (isFixed)
                {
                    fixedSize += size;
                }
                else
                {
                    fixedSize += size; // fixed portion (e.g., length prefix)
                    variableParts.Append($" + {variableExpr}");
                }
            }

            if (variableParts.Length == 0)
            {
                sb.AppendLine($"{indent}    public int GetSerializedSize() => {fixedSize};");
            }
            else
            {
                sb.AppendLine($"{indent}    public int GetSerializedSize()");
                sb.AppendLine($"{indent}        => {fixedSize}{variableParts};");
            }
        }

        private static void EmitSerialize(StringBuilder sb, DataAssetTypeInfo info, string indent)
        {
            sb.AppendLine($"{indent}    public void Serialize(ref SpanWriter writer)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        writer.WriteInt32(this.AssetId);");

            foreach (var field in info.Fields)
                EmitHelper.EmitSerializeField(sb, field, $"{indent}        ");

            sb.AppendLine($"{indent}    }}");
        }

        private static void EmitDeserialize(StringBuilder sb, DataAssetTypeInfo info, string indent)
        {
            sb.AppendLine($"{indent}    public static {info.TypeName} Deserialize(ref SpanReader reader)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        int __assetId = reader.ReadInt32();");
            sb.AppendLine($"{indent}        var __asset = new {info.TypeName}(__assetId);");

            foreach (var field in info.Fields)
                EmitHelper.EmitDeserializeField(sb, field, $"{indent}        ", "__asset");

            sb.AppendLine($"{indent}        return __asset;");
            sb.AppendLine($"{indent}    }}");
        }

        private static void EmitRegistrar(StringBuilder sb, DataAssetTypeInfo info)
        {
            var fullTypeName = info.Namespace != null
                ? $"{info.Namespace}.{info.TypeName}"
                : info.TypeName;

            sb.AppendLine($"internal static class {info.TypeName}Registrar");
            sb.AppendLine("{");
            sb.AppendLine("    [ModuleInitializer]");
            sb.AppendLine("    internal static void Register()");
            sb.AppendLine("    {");
            sb.AppendLine($"        DataAssetTypeRegistry.Register(");
            sb.AppendLine($"            {fullTypeName}.TYPE_ID,");
            sb.AppendLine($"            typeof({fullTypeName}),");
            sb.AppendLine($"            __Deserialize);");
            sb.AppendLine($"        xpTURN.Klotho.Core.WarmupRegistry.RegisterDataAsset({fullTypeName}.TYPE_ID);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    private static IDataAsset __Deserialize(ref SpanReader reader)");
            sb.AppendLine($"        => {fullTypeName}.Deserialize(ref reader);");
            sb.AppendLine("}");
        }
    }
}
