using System.Text;
using xpTURN.Klotho.Generator.Model;

namespace xpTURN.Klotho.Generator.Emitters
{
    internal static class EntityEmitter
    {
        public static string Emit(SerializableTypeInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using xpTURN.Klotho.Deterministic.Math;");
            sb.AppendLine("using xpTURN.Klotho.Serialization;");
            sb.AppendLine();

            if (info.Namespace != null)
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            var indent = info.Namespace != null ? "    " : "";
            sb.AppendLine($"{indent}partial class {info.TypeName}");
            sb.AppendLine($"{indent}{{");

            if (info.TypeId.HasValue)
            {
                sb.AppendLine($"{indent}    public const int TYPE_ID = {info.TypeId.Value};");
                sb.AppendLine($"{indent}    public override int EntityTypeId => TYPE_ID;");
                sb.AppendLine();
            }

            EmitHelper.EmitGetSerializedSize(sb, info, indent);
            sb.AppendLine();
            EmitSerializeCustomState(sb, info, indent);
            sb.AppendLine();
            EmitDeserializeCustomState(sb, info, indent);
            sb.AppendLine();
            EmitGetCustomStateHash(sb, info, indent);

            sb.AppendLine($"{indent}}}");

            if (info.Namespace != null)
                sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitSerializeCustomState(StringBuilder sb, SerializableTypeInfo info, string indent)
        {
            sb.AppendLine($"{indent}    protected override void SerializeCustomState(ref SpanWriter writer)");
            sb.AppendLine($"{indent}    {{");

            foreach (var field in info.Fields)
            {
                EmitHelper.EmitSerializeField(sb, field, $"{indent}        ");
            }

            sb.AppendLine($"{indent}    }}");
        }

        private static void EmitDeserializeCustomState(StringBuilder sb, SerializableTypeInfo info, string indent)
        {
            sb.AppendLine($"{indent}    protected override void DeserializeCustomState(ref SpanReader reader)");
            sb.AppendLine($"{indent}    {{");

            foreach (var field in info.Fields)
            {
                EmitHelper.EmitDeserializeField(sb, field, $"{indent}        ");
            }

            sb.AppendLine($"{indent}    }}");
        }

        private static void EmitGetCustomStateHash(StringBuilder sb, SerializableTypeInfo info, string indent)
        {
            sb.AppendLine($"{indent}    protected override ulong GetCustomStateHash(ulong hash)");
            sb.AppendLine($"{indent}    {{");

            foreach (var field in info.Fields)
            {
                if (!field.IncludeInHash)
                    continue;

                var hashExpr = EmitHelper.GetHashExpression(field);
                if (hashExpr != null)
                {
                    sb.AppendLine($"{indent}        {hashExpr}");
                }
            }

            sb.AppendLine($"{indent}        return hash;");
            sb.AppendLine($"{indent}    }}");
        }
    }
}
