using System.Text;
using xpTURN.Klotho.Generator.Model;
using xpTURN.Klotho.Generator.Utils;

namespace xpTURN.Klotho.Generator.Emitters
{
    internal static class EventEmitter
    {
        public static string Emit(SerializableTypeInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine();

            if (info.Namespace != null)
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            var indent = info.Namespace != null ? "    " : "";
            sb.AppendLine($"{indent}partial class {info.TypeName}");
            sb.AppendLine($"{indent}{{");

            if (info.TypeId.HasValue)
            {
                sb.AppendLine($"{indent}    public const int TYPE_ID = {info.TypeId.Value};");
                sb.AppendLine($"{indent}    public override int EventTypeId => TYPE_ID;");
                sb.AppendLine();
            }

            EmitGetContentHash(sb, info, indent);
            sb.AppendLine();
            EmitReset(sb, info, indent);

            sb.AppendLine($"{indent}}}");

            if (info.Namespace != null)
                sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitGetContentHash(StringBuilder sb, SerializableTypeInfo info, string indent)
        {
            sb.AppendLine($"{indent}    public override long GetContentHash()");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        unchecked");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            long hash = unchecked((long)14695981039346656037UL);");
            sb.AppendLine($"{indent}            hash ^= EventTypeId; hash *= 1099511628211L;");

            foreach (var field in info.Fields)
            {
                if (!field.IncludeInHash)
                    continue;

                sb.AppendLine($"{indent}            hash ^= (long)this.{field.Name}.GetHashCode(); hash *= 1099511628211L;");
            }

            sb.AppendLine($"{indent}            return hash;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
        }

        private static void EmitReset(StringBuilder sb, SerializableTypeInfo info, string indent)
        {
            sb.AppendLine($"{indent}    public override void Reset()");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        base.Reset();");

            foreach (var field in info.Fields)
            {
                var defaultVal = GetDefaultValue(field.TypeFullName);
                sb.AppendLine($"{indent}        this.{field.Name} = {defaultVal};");
            }

            sb.AppendLine($"{indent}    }}");
        }

        private static string GetDefaultValue(string typeFullName)
        {
            switch (typeFullName)
            {
                case "bool":
                case "System.Boolean":
                    return "false";
                case "long":
                case "System.Int64":
                case "ulong":
                case "System.UInt64":
                    return "0L";
                case "float":
                case "System.Single":
                    return "0f";
                case "double":
                case "System.Double":
                    return "0d";
                case "string":
                case "System.String":
                case "byte[]":
                case "System.Byte[]":
                    return "null";
                default:
                    // Numeric primitives such as int, byte, short are 0
                    if (TypeMappings.TryGetMapping(typeFullName, out var mapping) && mapping.Size > 0)
                        return "default";
                    // EntityRef, custom struct, etc.
                    return "default";
            }
        }
    }
}
