using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using xpTURN.Klotho.Generator.Model;

namespace xpTURN.Klotho.Generator.Emitters
{
    internal static class FactoryEmitter
    {
        public static string Emit(ImmutableArray<SerializableTypeInfo> types,
            bool hasEntityFactory, bool hasCommandFactory, bool hasMessageSerializer)
        {
            var entities = hasEntityFactory
                ? types.Where(t => t.Category == TypeCategory.Entity && t.TypeId.HasValue).ToList()
                : new List<SerializableTypeInfo>();
            var commands = types.Where(t => t.Category == TypeCategory.Command && t.TypeId.HasValue).ToList();
            var messages = types.Where(t => t.Category == TypeCategory.Message && t.MessageTypeEnum != null).ToList();

            if (entities.Count == 0 && commands.Count == 0 && messages.Count == 0)
                return null;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine();

            if (entities.Count > 0)
            {
                sb.AppendLine("namespace xpTURN.Klotho.State");
                sb.AppendLine("{");
                sb.AppendLine("    partial class EntityFactory");
                sb.AppendLine("    {");
                sb.AppendLine("        static partial void RegisterGeneratedTypes(EntityFactory factory)");
                sb.AppendLine("        {");
                foreach (var e in entities)
                {
                    sb.AppendLine($"            factory.RegisterEntityType<{e.FullTypeName}>({e.FullTypeName}.TYPE_ID);");
                }
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");
                sb.AppendLine();
            }

            if (commands.Count > 0)
            {
                if (hasCommandFactory)
                {
                    // Same assembly as CommandFactory — use partial method
                    sb.AppendLine("namespace xpTURN.Klotho.Core");
                    sb.AppendLine("{");
                    sb.AppendLine("    public partial class CommandFactory");
                    sb.AppendLine("    {");
                    sb.AppendLine("        static partial void RegisterGeneratedTypes(CommandFactory factory)");
                    sb.AppendLine("        {");
                    foreach (var c in commands)
                    {
                        sb.AppendLine($"            factory.RegisterCommand<{c.FullTypeName}>({c.FullTypeName}.TYPE_ID);");
                    }
                    sb.AppendLine("        }");
                    sb.AppendLine("    }");
                    sb.AppendLine("}");
                }
                else
                {
                    // Cross-assembly — use [ModuleInitializer] + CommandRegistry
                    sb.AppendLine("using System.Runtime.CompilerServices;");
                    sb.AppendLine("using xpTURN.Klotho.Core;");
                    sb.AppendLine();
                    sb.AppendLine("internal static class CommandRegistrar");
                    sb.AppendLine("{");
                    sb.AppendLine("    [ModuleInitializer]");
                    sb.AppendLine("    internal static void Register()");
                    sb.AppendLine("    {");
                    foreach (var c in commands)
                    {
                        sb.AppendLine($"        CommandRegistry.Register<{c.FullTypeName}>({c.FullTypeName}.TYPE_ID);");
                    }
                    sb.AppendLine("    }");
                    sb.AppendLine("}");
                }
                sb.AppendLine();
            }

            if (messages.Count > 0)
            {
                if (hasMessageSerializer)
                {
                    // Same assembly as MessageSerializer — use partial method
                    sb.AppendLine("namespace xpTURN.Klotho.Network");
                    sb.AppendLine("{");
                    sb.AppendLine("    partial class MessageSerializer");
                    sb.AppendLine("    {");
                    sb.AppendLine("        static partial void RegisterGeneratedTypes(MessageSerializer serializer)");
                    sb.AppendLine("        {");
                    foreach (var m in messages)
                    {
                        sb.AppendLine($"            serializer.RegisterMessageType<{m.FullTypeName}>(NetworkMessageType.{m.MessageTypeEnum});");
                    }
                    sb.AppendLine("        }");
                    sb.AppendLine("    }");
                    sb.AppendLine("}");
                }
                else
                {
                    // Cross-assembly — use [ModuleInitializer] + MessageRegistry
                    // Wrap in namespace xpTURN.Klotho.Generated to avoid global class name collisions.
                    // Place using inside the namespace block — after emitting CommandRegistrar (global class) above,
                    // an external using directive would trigger CS1529.
                    sb.AppendLine("namespace xpTURN.Klotho.Generated");
                    sb.AppendLine("{");
                    sb.AppendLine("    using System.Runtime.CompilerServices;");
                    sb.AppendLine("    using xpTURN.Klotho.Network;");
                    sb.AppendLine();
                    sb.AppendLine("    internal static class MessageRegistrar");
                    sb.AppendLine("    {");
                    sb.AppendLine("        [ModuleInitializer]");
                    sb.AppendLine("        internal static void Register()");
                    sb.AppendLine("        {");
                    foreach (var m in messages)
                    {
                        sb.AppendLine($"            MessageRegistry.Register<{m.FullTypeName}>(NetworkMessageType.{m.MessageTypeEnum});");
                    }
                    sb.AppendLine("        }");
                    sb.AppendLine("    }");
                    sb.AppendLine("}");
                }
            }

            return sb.ToString();
        }
    }
}
