using System.Collections.Immutable;
using System.Linq;
using System.Text;
using xpTURN.Klotho.Generator.Model;

namespace xpTURN.Klotho.Generator.Emitters
{
    internal static class WarmupEmitter
    {
        public static string Emit(ImmutableArray<SerializableTypeInfo> types)
        {
            var commands = types.Where(t => t.Category == TypeCategory.Command && t.TypeId.HasValue).ToList();
            var events   = types.Where(t => t.Category == TypeCategory.Event).ToList();
            var messages = types.Where(t => t.Category == TypeCategory.Message).ToList();

            if (commands.Count == 0 && events.Count == 0 && messages.Count == 0)
                return null;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using xpTURN.Klotho.Core;");
            sb.AppendLine();
            sb.AppendLine("internal static class KlothoWarmupRegistrar");
            sb.AppendLine("{");
            sb.AppendLine("    [ModuleInitializer]");
            sb.AppendLine("    internal static void Register()");
            sb.AppendLine("    {");
            foreach (var c in commands)
                sb.AppendLine($"        WarmupRegistry.RegisterCommand<{c.FullTypeName}>({c.FullTypeName}.TYPE_ID);");
            foreach (var e in events)
                sb.AppendLine($"        WarmupRegistry.RegisterEvent<{e.FullTypeName}>();");
            foreach (var m in messages)
                sb.AppendLine($"        WarmupRegistry.RegisterMessage<{m.FullTypeName}>();");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
